# This file represents your module.


# FUNCION RANDOM NUMBER GENERATOR:
def Random_n_g ():
    """ Next line is not needed if you wrote it before. Consider deletion."""
    import numpy as np
    # Return list with random integers from low (inclusive) to high (exclusive).
    number = np.random.randint(0, high=10, size=4, dtype=int)
    # Group the four elements in the list to a str
    strings = [str(num) for num in number]
    a_string = "".join(strings)
    # In the lines below we can modify number value to int (= int(a_string))
    # but remember int removes the 'left sided' ceros.
    number = (a_string)
    print(number)


# Download data from url
def pabajo (url):
    import requests 
    url= input("introduce una url")
   # n = input ("introduce un id para el paquete")
    paquete = requests.get(url).content
print(paquete)      



# FUNCION QUE IMPORTA ARCHIVO TSV Y LO TRANSFORMA EN DATA FRAME
def tsv_df (x):
# This line is not needed if you wrote before. Consider deletion.
    import pandas as pd
    import numpy as np

# Import tsv file.
    import requests 
    url="https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

# Read the file with panda read_csv and delete the delimiters. Create a variable wich is a list with all the data
    x = pd.read_csv(url, delimiter = "\t")
    print (x)

# Set up the data in columns and rows with an index and so.. aka magic panda's DataFrame
    dfr = pd.DataFrame(data=x)
    dfr

# Group list by item name and adding numeric values to get the sum
"""TODO some trash can be generated by this function.
Need to delete useless data 
or skip columns by just selecting the columns i need to check"""
    dfr = x.groupby(['column_name']).sum()
    print(dfr)